# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 5,10,14,15,20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export current_year=`date +%Y`
          export current_mouth=`date +%m`
          export current_day=`date +%d`
          export file_name="${current_mouth}_${current_day}_${current_year}.txt"
          
          mkdir -p data
          
          head -c 32 /dev/urandom > data/$file_name
          
          git config --global user.email "lqcqgnwxke@mikios.shop"
          git config --global user.name "lqcqgnwxke"
          git add .
          git commit -m '23123'
          git push
          git config --global user.email "ljjgnfrzmj@kwsmail.tech"
          git config --global user.name "selDeFipowerELX"
